sudo: false
language: 
  java
jdk:
  - openjdk8

cache:
  directories:
   - $HOME/.m2

deploy:
  provider: script
  script: "mvn clean package deploy -DmuleDeploy"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    recipients:
    - kalidass@integralzone.com
    on_success: change
    on_failure: always